### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by mkhezr** [vslavik/xmlwrapp#30]
installing on OS X El Capitan 10.11.2

I have libxml2 and libxslt installed using homebrew and since the installations are keg-only (not symlinked), I hade to provide LDFLAGS and CPPFLAGS for ./configure to work properly. Here is the command that succeeded:

`./configure LDFLAGS=-L/usr/local/opt/libxml2/lib CPPFLAGS=-I/usr/local/opt/libxml2/include`

and then I ran make and the following error showed up:
```
Making all in include
make[1]: Nothing to be done for `all'.
Making all in src
  CXX      libxml/libxmlwrapp_la-ait_impl.lo
In file included from libxml/ait_impl.cxx:34:

libxml/ait_impl.h:42:10: fatal error: 'libxml/tree.h' file not found
#include <libxml/tree.h>

         ^
1 error generated.
make[1]: *** [libxml/libxmlwrapp_la-ait_impl.lo] Error 1
      make: *** [all-recursive] Error 1
```

Please advise.

**Comment by vslavik** [comment]
> Please advise.

Fix your build environment. Don’t do weird things. If a problem happens, investigate using the tools at your disposal: here, that would be `config.log` and make output (with automake’s usual `make V=1`).

Your `CPPFLAGS` are obviously wrong, which you can check easily:
```
$ ls /usr/local/opt/libxml2/include/
libxml2
$ ls /usr/local/opt/libxml2/include/libxml2/libxml/
DOCBparser.h       debugXML.h         nanohttp.h         tree.h             xmlexports.h       xmlstring.h
…
```

The *real* question is how `configure` even passed. And that’s because there’s Homebrew-created/provided `/usr/local/Library/ENV/pkgconfig/10.11/libxml-2.0.pc` that is found (due to, I assume, some Homebrew patch) and this file’s content is obviously broken, because it claims to have headers in `/usr/include` which doesn’t exist.

So you need to make your build environment sane, by doing one of the following:

1. Use proper SDK root (`-isysroot`) in your `CFLAGS` so that SDK-provided libxml2 is found.
2. Force Homebrew to behave (with the helpfully named `--force` flag to the link command).
3. Use a better-behaved package manager instead.

The latter is certainly fine, the former may be.
