### ISSUE TITLE
Please clarify your license 

### ISSUE THREAD

**Issue by npac** [vslavik/xmlwrapp#51]
Reading your LICENCE file i was not able to correlate it with any other existing licences. 
Is this supposed to be an Apache licence? if yes could you please mention this. 
Thanks.

**Comment by vadz** [comment]
This is BSD 3-clause licence. I'm not sure why it isn't automatically flagged as such by Github.

**Comment by vslavik** [comment]
According to [GitHub docs](https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#detecting-a-license), [this software](https://github.com/licensee/licensee) is used for license detection and uses data from https://choosealicense.com; it performs loose textual match on license texts.

It turns out that BSD-3-Clause license uses the "copyright holder" term (the above site and OSI [both](https://choosealicense.com/licenses/bsd-3-clause/) [agree](https://opensource.org/licenses/BSD-3-Clause)); this difference occurs 3 times, causing the matching to fail, and this minimal patch addresses it:

```diff
diff --git a/LICENSE b/LICENSE
index 323ed9f..c5d8298 100644
--- a/LICENSE
+++ b/LICENSE
@@ -13,14 +13,14 @@ are met:
    notice, this list of conditions and the following disclaimer in
    the documentation and/or other materials provided with the
    distribution.
-3. Neither the name of the Author nor the names of its contributors
+3. Neither the name of the copyright holder nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.
 
-THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS''
+THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
 TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
-PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR
+PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER
 OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
@@ -29,3 +29,4 @@ AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 SUCH DAMAGE.
```

(I think reformatting to follow the common plaintext rendering would be good too.)

This seems reasonable and meaning-unchanging changed to make to me. Not as such to make GitHub happy, but because the term "copyright holder" is clearer and eliminating non-standard wording is worthy in itself, isn't it?

**Comment by vadz** [comment]
Yes, I think this should be done just to avoid any spurious divergences with the standard licence.

BTW, we need to update the years in this file too, this was last done 4 years ago...
